export default {
  id: "nvidia",
  priority: 20,
  hasFree: true,
  alias: "nvidia",
  display: {
    name: "NVIDIA NIM",
    icon: "developer_board",
    color: "#76B900",
    textIcon: "NV",
    website: "https://developer.nvidia.com/nim",
    notice: {
      text: "Free access for NVIDIA Developer Program members (prototyping & testing).",
      apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://integrate.api.nvidia.com/v1/chat/completions",
    validateUrl: "https://integrate.api.nvidia.com/v1/models",
  },
  models: [
    { id: "z-ai/glm-5.2", name: "GLM 5.2" },
    { id: "minimaxai/minimax-m3", name: "MiniMax M3" },
    { id: "minimaxai/minimax-m2.7", name: "MiniMax M2.7" },
    { id: "deepseek-ai/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-ai/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra 550B" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "Nemotron 3 Super 120B" },
    { id: "mistralai/mistral-large-3-675b-instruct-2512", name: "Mistral Large 3 675B" },
    { id: "mistralai/mistral-small-4-119b-2603", name: "Mistral Small 4 119B" },
    { id: "mistralai/devstral-2-123b-instruct-2512", name: "Devstral 2 123B" },
    { id: "mistralai/ministral-14b-instruct-2512", name: "Ministral 14B" },
    { id: "mistralai/mistral-medium-3.5-128b", name: "Mistral Medium 3.5 128B" },
    { id: "mistralai/mixtral-8x7b-instruct-v0.1", name: "Mixtral 8x7B" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen3.5 397B A17B" },
    { id: "qwen/qwen3.5-122b-a10b", name: "Qwen3.5 122B A10B" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80B A3B" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "openai/gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "google/gemma-4-31b-it", name: "Gemma 4 31B" },
    { id: "google/gemma-2-2b-it", name: "Gemma 2 2B" },
    { id: "meta/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick 17B" },
    { id: "meta/llama-3.1-8b-instruct", name: "Llama 3.1 8B" },
    { id: "meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B" },
    { id: "meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B" },
    { id: "meta/llama-3.2-11b-vision-instruct", name: "Llama 3.2 11B Vision" },
    { id: "meta/llama-3.2-90b-vision-instruct", name: "Llama 3.2 90B Vision" },
    { id: "stepfun-ai/step-3.5-flash", name: "Step 3.5 Flash" },
    { id: "stepfun-ai/step-3.7-flash", name: "Step 3.7 Flash" },
    { id: "abacusai/dracarys-llama-3.1-70b-instruct", name: "Dracarys Llama 3.1 70B" },
    { id: "upstage/solar-10.7b-instruct", name: "Solar 10.7B" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "Nemotron 3 Nano 30B" },
    { id: "nvidia/nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12B v2 VL" },
    { id: "nvidia/llama-3.3-nemotron-super-49b-v1", name: "Nemotron Super 49B v1" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", kind: "embedding" },
    { id: "nvidia/parakeet-ctc-1.1b-asr", name: "Parakeet CTC 1.1B", params: ["language"], kind: "stt" },
    { id: "fastpitch", name: "FastPitch", kind: "tts" },
    { id: "tacotron2", name: "Tacotron2", kind: "tts" },
  ],
  serviceKinds: ["llm","tts","embedding"],
  ttsConfig: {
    baseUrl: "https://integrate.api.nvidia.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "nvidia-tts",
  },
  embeddingConfig: { baseUrl: "https://integrate.api.nvidia.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
};
